[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_fall_transfer_hook = "JuLq45VkzwMX5dmxrNLppkomv3VJxc4xjuVF1BWFibx"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
